import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";


export const metadata = {
  title: "Dashboard",
  description: "Generated by create dashboard app",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans flex`}>
        <Sidebar />

        <div className="flex-1 flex flex-col">
          <Navbar />

          
          <main className="p-6 bg-[#162456] min-h-screen">{children}</main>
        </div>
      </body>
    </html>
  );
}
